name: "Stale issues"
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  stale:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR is stale because it has been labeled with inactivity.'
        exempt-pr-labels: 'lifecycle/active'
        stale-pr-label: 'lifecycle/stale'
        days-before-stale: '0.001'
        days-before-close: 2
        days-before-issue-stale: '-1'
        days-before-issue-close: '-1'
